services:
  reverse-proxy:
    image: traefik:v3.1
    command: 
      - "--api.insecure=true"
      - "--providers.docker"
      - "--entrypoints.web.address=:80"
      - "--entryPoints.websecure.address=:443"
      - "--log.level=DEBUG"
      - "--log.filePath=/logs/traefik.log"
      - "--accesslog.filePath=/logs/access.log"
      - "--accesslog.format=json"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=mail@rich-calculations.net"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      # The https port
      - "433:433"
      # The http port
      - "80:80"
      # Dashboard
      - "8080:8080"
    volumes: 
      # So that traefik can listen to Docker events
      - /var/run/docker.sock:/var/run/docker.sock
      - letsencrypt:/letsencrypt
      - ./logs:/logs
  rich-darts:
    image: registry.digitalocean.com/rich-registry/rich-darts
    container_name: prod
    labels:
      - "traefik.enable=true"
      # hack: using the url caused problems with forwarding of united domains
      - "traefik.http.routers.rich-darts.rule=PathPrefix(`/`)"
      - "traefik.http.routers.rich-darts.entrypoints=websecure"
      - "traefik.http.routers.rich-darts.tls.resolver=myresolver"
      - "traefik.http.services.rich-darts.loadbalancer.server.port=8080"
    #ports:  
      #- "8080:8080"
    environment:
      DATABASE_URL: "/home/richDarts.db"
      LOG_URL: "/home/server.log"
    volumes:
      - sqlite:/home/
volumes:
  sqlite:
  letsencrypt:


