[application]

[web.app]

# HTML title tag content
title = "rich_darts"

# include `assets` in web platform
[web.resource]

# Additional CSS style files
style = []

# Additional JavaScript files
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []

[bundle]
publisher = "rich-darts"
identifier = "com.rich-darts"
